version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
  api:
    build: ./backend/TrungTinElectronicsAPI
    container_name: trungtin-api
    depends_on:
      - sqlserver
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Production"
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: "trungtinelectronics"
      Jwt__Audience: "trungtinelectronics"
      ConnectionStrings__DefaultConnection: ${CONNECTION_STRING}
      CloudinarySettings__CloudName: ${CLOUDINARY_CLOUD_NAME}
      CloudinarySettings__ApiKey: ${CLOUDINARY_API_KEY}
      CloudinarySettings__ApiSecret: ${CLOUDINARY_API_SECRET}
      Google__ClientId: ${GOOGLE_CLIENT_ID}
volumes:
  sql_data: